FROM python:3.8

COPY requirements/requirements-ui.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY img_classification/ui img_classification/ui
ENTRYPOINT ["streamlit", "run", "--server.fileWatcherType", "none", "img_classification/ui/app.py"]